# Tensorflow Basics

In [1]:
import tensorflow as tf
print("TensorFlow Version:{} ".format(tf.__version__))
print(__doc__)

TensorFlow Version:2.5.0 
Automatically created module for IPython interactive environment


__Tensoren verallgemeinern__ Skalare, Vektoren und Matrizen in höheren Dimensionen.

In [2]:
# Skalar
print(tf.constant(5)) 
# Vektor
print(tf.constant([2,3])) 
# Matrix 2x2
print(tf.constant([[1,2],
                   [3,4]]))
# Matrix 3x3
print(tf.constant([[1,2,3],
                   [3,4,5],
                   [6,7,8]]))
# 3D-Tensor
print(tf.constant([[[1,4],[5,2]],
                   [[3,5],[9,8]]]))

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[[1 4]
  [5 2]]

 [[3 5]
  [9 8]]], shape=(2, 2, 2), dtype=int32)


__Tensorflow-Tensoren__ die schnelleren Numpy-Arrays

In [3]:
import numpy as np

# numpy array
a = np.array([1,2,3])
print(a)

# konstanter Tensor 
tc = tf.constant([1,2,3])
print(tc)

# änderbarer Tensor
tm = tf.Variable([1,2,3])
print(tm)

# ändern mit assign
tm.assign([4,5,6])
print(tm)

#internen Typ ändern, Achtung danach ist tm ein konstanter Tensor
tm = tf.cast(tm, tf.float64) 
print(tm)



[1 2 3]
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6])>
tf.Tensor([4. 5. 6.], shape=(3,), dtype=float64)


Änderbare Tensoren besitzen ähnliche API wie Numpy-Arrays. 

In [4]:
t = tf.random.uniform([3])
print("Tensor t = ",t)

# als Spaltenvektor 
x = t[:, tf.newaxis]
print("x = ",x)

# als Zeilenvektor
y = t[tf.newaxis, :]
print("y = ",y)


Tensor t =  tf.Tensor([0.2936554  0.1363082  0.11058331], shape=(3,), dtype=float32)
x =  tf.Tensor(
[[0.2936554 ]
 [0.1363082 ]
 [0.11058331]], shape=(3, 1), dtype=float32)
y =  tf.Tensor([[0.2936554  0.1363082  0.11058331]], shape=(1, 3), dtype=float32)


## Konvertieren von Numpy-Arrays und Tensoren

In [5]:
from PIL import Image

# Bild öffnen, img ist ein numpy array 
img = Image.open("cat.jpg")
# Konvertierung in NumPy-Array
img_data = np.asarray( img, dtype="int32" )
# Konvertierung in einen Tensor
img_tensor = tf.convert_to_tensor(img_data, dtype=tf.int32)
img_tensor


<tf.Tensor: shape=(224, 224, 3), dtype=int32, numpy=
array([[[134, 132, 119],
        [135, 133, 120],
        [136, 134, 121],
        ...,
        [119, 116, 101],
        [116, 113,  98],
        [114, 111,  96]],

       [[136, 134, 121],
        [136, 134, 121],
        [137, 135, 122],
        ...,
        [120, 117, 102],
        [117, 114,  99],
        [116, 113,  98]],

       [[137, 135, 122],
        [138, 136, 123],
        [138, 136, 123],
        ...,
        [121, 118, 103],
        [119, 116, 101],
        [117, 114,  99]],

       ...,

       [[196, 180, 155],
        [198, 182, 157],
        [201, 184, 164],
        ...,
        [111,  95,  72],
        [115,  97,  75],
        [118, 100,  76]],

       [[197, 181, 156],
        [199, 183, 158],
        [200, 183, 163],
        ...,
        [109,  94,  73],
        [109,  92,  72],
        [109,  93,  70]],

       [[198, 182, 157],
        [199, 183, 158],
        [200, 183, 163],
        ...,
        [108,  93,  7

In [6]:
# mit Tensorflow Bild einlesen und in numpy array umwandeln
img = tf.image.decode_jpeg(tf.io.read_file("cat.jpg"))

print(tf.rank(img))
print(tf.shape(img))


tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([224 224   3], shape=(3,), dtype=int32)


## Tensor-Operationen

In [7]:
import tensorflow as tf
print(tf.ones((1, 2, 3)))
print(tf.zeros((1, 2, 3)))
print(tf.eye(3))


tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [8]:
tensor = tf.ones((1, 2))
print(tensor.shape)
print(tensor.ndim)
print(tensor[0])
print(tf.size(tensor))
print(tensor.dtype)
print(tensor.shape[-1])


(1, 2)
2
tf.Tensor([1. 1.], shape=(2,), dtype=float32)
tf.Tensor(2, shape=(), dtype=int32)
<dtype: 'float32'>
2


In [9]:
import tensorflow as tf
a = tf.constant([1, 2, 3, 4],
shape=(2, 2))
b = tf.constant([1, 2, 3, 4],
shape=(2, 2))
print(a @ b)
print(tf.matmul(a, b))
print(tf.transpose(a))
print(tf.reshape(a, shape=(1,4)))

tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)
tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)


In [10]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])
            
# softmax Funktion normiert Tensoren 
print(tf.nn.softmax(x, axis=-1))
print(tf.concat([x, x, x], axis=0))
print(tf.reduce_sum(x))

tf.Tensor(
[[0.09003057 0.24472848 0.66524094]
 [0.09003057 0.24472848 0.66524094]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [4. 5. 6.]], shape=(6, 3), dtype=float32)
tf.Tensor(21.0, shape=(), dtype=float32)


Falls __GPU-Unterstützung__ vorhanden, kann Tensorflow diese verwenden.

In [11]:
if tf.config.list_physical_devices('GPU'):
  print("TensorFlow **IS** using the GPU")
else:
  print("TensorFlow **IS NOT** using the GPU")

TensorFlow **IS NOT** using the GPU
